PullUpDomain\Entity\ExerciseVariant:
    exclusion_policy: ALL
    properties:
        name:
            groups: [logger, exercise_variant_item, exercise_variant_list]
            expose: true

        description:
            groups: [logger, exercise_variant_item, exercise_variant_list]
            expose: true

    virtual_properties:
        getId:
            serialized_name: id
            type: string
            groups: [logger, exercise_variant_item, exercise_variant_list]
            expose: true

        getTranslations:
            serialized_name: translations
            type: array
            groups: [exercise_variant_item, exercise_variant_list]
            expose: true