PullUpDomain\Entity\Exercise:
    exclusion_policy: ALL
    properties:
        name:
            groups: [logger, exercise_item, exercise_list]
            expose: true

    virtual_properties:
        getId:
            serialized_name: id
            type: string
            groups: [logger, exercise_item, exercise_list]
            expose: true