PullUpDomain\Entity\Goal:
    exclusion_policy: ALL
    properties:
        name:
            groups: [logger, goal_item, goal_list]
            expose: true

        description:
            groups: [logger, goal_item, goal_list]
            expose: true

        requiredSets:
            groups: [logger, goal_item, goal_list]
            expose: true

        requiredReps:
            groups: [logger, goal_item, goal_list]
            expose: true

        requiredWeight:
            groups: [logger, goal_item, goal_list]
            expose: true

        description:
            groups: [logger, goal_item, goal_list]
            expose: true

        exercise:
            groups: [exercise_item]
            expose: true

        exerciseVariant:
            groups: [exercise_variant_item]
            expose: true

        createdAt:
            groups: [logger, goal_item, goal_list]
            expose: true

        updatedAt:
            groups: [logger, goal_item, goal_list]
            expose: true

    virtual_properties:
        getId:
            serialized_name: id
            type: string
            groups: [logger, goal_item, goal_list]
            expose: true

        getRequiredType:
            serialized_name: required_type
            type: string
            groups: [logger, goal_item, goal_list]
            expose: true

        getSets:
            serialized_name: sets
            type: array
            groups: [logger, goal_item, goal_list]
            expose: true

        getRequiredAmount:
            serialized_name: required_amount
            type: string
            groups: [logger, goal_item, goal_list]
            expose: true

        getLastSetValue:
            serialized_name: last_set_value
            type: string
            groups: [logger, goal_item, goal_list]
            expose: true

        doneThisCircuit:
            serialized_name: done_this_circuit
            type: string
            groups: [logger, goal_item, goal_list]
            expose: true

        leftThisCircuit:
            serialized_name: left_this_circuit
            type: string
            groups: [logger, goal_item, goal_list]
            expose: true