PullUpDomain\Entity\GoalSet:
    exclusion_policy: ALL
    properties:
        createdAt:
            groups: [logger, goal_set_item, goal_set_list]
            expose: true

        goal:
            groups: [logger, goal_set_item]
            expose: true

    virtual_properties:
        getId:
            serialized_name: id
            type: string
            groups: [logger, goal_set_item, goal_set_list]
            expose: true

        getValue:
            serialized_name: value
            type: integer
            groups: [logger, goal_set_item, goal_set_list]
            expose: true

        getWeight:
            serialized_name: weight
            type: integer
            groups: [logger, goal_set_item, goal_set_list]
            expose: true