pullup_api_exercise_list:
      path:     /list
      defaults: { _controller: pullup.api.exercise.controller:listAction, _format: 'json'  }
      methods: [GET]

pullup_api_create_exercise:
      path:     /create
      defaults: { _controller: pullup.api.exercise.controller:createAction, _format: 'json'  }
      methods: [POST]

pullup_api_update_exercise:
      path:     /{id}/update
      defaults: { _controller: pullup.api.exercise.controller:updateAction, _format: 'json'  }
      methods: [PUT]
