pullup_api_goal_list:
      path:     /list
      defaults: { _controller: pullup.goal.controller:listAction, _format: 'json'  }
      methods: [GET]

pullup_api_goal_create:
      path:     /create
      defaults: { _controller: pullup.goal.controller:createAction, _format: 'json'  }
      methods: [POST]

pullup_api_goal_set_create:
      path:     /set/create
      defaults: { _controller: pullup.goal.controller:createSetAction, _format: 'json'  }
      methods: [POST]