pullup_api_user_list:
      path:     /secured/users
      defaults: { _controller: pullup.user.controller:listAction, _format: 'json'  }
      methods: [GET]

pullup_api_user_login_by_facebook:
      path:     /login/facebook
      defaults: { _controller: pullup.user.controller:loginByFacebookAction, _format: 'json'  }
      methods: [POST]