pullup_api_user_list:
      path:     /secured/users
      defaults: { _controller: pullup.api.user.controller:listAction, _format: 'json'  }
      methods: [GET]

pullup_api_user_login_by_facebook:
      path:     /login/facebook
      defaults: { _controller: pullup.api.user.controller:loginByFacebookAction, _format: 'json'  }
      methods: [POST]

pullup_api_user_register:
      path:     /register
      defaults: { _controller: pullup.api.user.controller:registerAction, _format: 'json'  }
      methods: [POST]

pullup_api_user_check_token:
      path:     /secured/check_token
      defaults: { _controller: pullup.api.user.controller:checkTokenAction, _format: 'json'  }
      methods: [GET]

pullup_api_user_password_remind:
      path:     /password-remind
      defaults: { _controller: pullup.api.user.controller:passwordRemindAction, _format: 'json'  }
      methods: [POST]

pullup_api_user_password_remind_key_validate:
      path:     /password-remind/{email}/{key}
      defaults: { _controller: pullup.api.user.controller:passwordRemindKeyValidateAction, _format: 'json'  }
      methods: [GET]

pullup_api_user_password_change:
      path:     /password-change
      defaults: { _controller: pullup.api.user.controller:passwordChangeAction, _format: 'json'  }
      methods: [POST]
