imports:
    - { resource: config.yml }

monolog:
    channels: ['command_process_circuits']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            channels: ['!command_process_circuits']
        command_process_circuits:
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/command_process_circuits.log'
            channels: ['command_process_circuits']
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!command_process_circuits']
        console:
            type: console
            process_psr_3_messages: false
