services:
    pullup.token.controller:
        class: PullUpBundle\Controller\Api\TokenController

    pullup.front.index.controller:
        class: PullUpBundle\Controller\Front\IndexController
        arguments:
            - "@templating"

    pullup.api.index.controller:
        class: PullUpBundle\Controller\Api\IndexController
        arguments:
            - "@templating"

    pullup.api.user.controller:
        class: PullUpBundle\Controller\Api\UserController
        arguments:
            - "@pullup.profile_manager"
            - "@pullup.command_bus"

    pullup.api.profile.controller:
        class: PullUpBundle\Controller\Api\ProfileController
        arguments:
            - "@pullup.profile_manager"
            - "@pullup.current_user"
            - "@pullup.command_bus"

    pullup.api.training_pull_up.controller:
        class: PullUpBundle\Controller\Api\TrainingPullUpController
        arguments:
            - "@pullup.current_user"
            - "@pullup.training_pull_up.service"
            - "@pullup.training_pull_up.service_history"
            - "@pullup.command_bus"

    pullup.api.exercise.controller:
        class: PullUpBundle\Controller\Api\ExerciseController
        arguments:
            - "@pullup.exercise.repository.doctrine"
            - "@pullup.current_user"
            - "@pullup.command_bus"

    pullup.api.goal.controller:
        class: PullUpBundle\Controller\Api\GoalController
        arguments:
            - "@pullup.goal.repository.doctrine"
            - "@pullup.goal_set.repository.doctrine"
            - "@pullup.section.repository.doctrine"
            - "@pullup.current_user"
            - "@pullup.command_bus"

    pullup.api.section.controller:
        class: PullUpBundle\Controller\Api\SectionController
        arguments:
            - "@pullup.section.repository"
            - "@pullup.current_user"
            - "@pullup.command_bus"

    pullup.api.settings.controller:
        class: PullUpBundle\Controller\Api\SettingsController
        arguments:
            - "@pullup.profile_manager"
            - "@pullup.current_user"
            - "@pullup.command_bus"
