services:
    pullup.login_by_facebook.handler:
        class: PullUpService\Handler\LoginByFacebookHandler
        arguments:
            - "@pullup.profile_manager"
            - "@pullup.profile_authentication_manager"
        tags:
            - { name: command_handler, handles: PullUpService\Command\LoginByFacebookCommand }

    pullup.create_first_form.handler:
        class: PullUpService\Handler\CreateFirstFormHandler
        arguments:
          - '@pullup.first_form.repository'
          - '@pullup.current_user'
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\CreateFirstFormCommand }

    pullup.submit_training_pull_up.handler:
        class: PullUpService\Handler\SubmitTrainingPullUpHandler
        arguments:
          - '@pullup.training_pull_up.repository'
          - '@pullup.current_user'
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\SubmitTrainingPullUpCommand }

    pullup.create_goal.handler:
        class: PullUpService\Handler\CreateGoalHandler
        arguments:
          - '@pullup.goal.repository'
          - '@pullup.exercise.repository'
          - '@pullup.current_user'
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\CreateGoalCommand }