services:
    pullup.login_by_facebook.handler:
        class: PullUpService\Handler\LoginByFacebookHandler
        arguments:
            - "@pullup.profile_manager"
            - "@pullup.profile_authentication_manager"
        tags:
            - { name: command_handler, handles: PullUpService\Command\LoginByFacebookCommand }

    pullup.register.handler:
        class: PullUpService\Handler\RegisterHandler
        arguments:
            - "@pullup.profile_manager"
            - "@pullup.profile_authentication_manager"
        tags:
            - { name: command_handler, handles: PullUpService\Command\RegisterCommand }

    pullup.password_reminder.handler:
        class: PullUpService\Handler\PasswordRemindHandler
        arguments:
            - "@pullup.profile_manager"
            - "@mailer"
            - "@router"
            - "@templating"
        tags:
            - { name: command_handler, handles: PullUpService\Command\PasswordRemindCommand }

    pullup.password_reminder_key_validate.handler:
        class: PullUpService\Handler\PasswordRemindKeyValidateHandler
        arguments:
            - "@request_stack"
            - "@pullup.profile_manager"
        tags:
            - { name: command_handler, handles: PullUpService\Command\PasswordRemindKeyValidateCommand }

    pullup.password_change.handler:
        class: PullUpService\Handler\PasswordChangeHandler
        arguments:
            - "@pullup.profile_manager"
        tags:
            - { name: command_handler, handles: PullUpService\Command\PasswordChangeCommand }

    pullup.create_first_form.handler:
        class: PullUpService\Handler\CreateTrainingPullUpFirstFormHandler
        arguments:
          - '@pullup.training_pull_up_first_form.repository'
          - '@pullup.current_user'
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\CreateTrainingPullUpFirstFormCommand }

    pullup.submit_training_pull_up.handler:
        class: PullUpService\Handler\SubmitTrainingPullUpHandler
        arguments:
          - '@pullup.training_pull_up.repository'
          - '@pullup.current_user'
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\SubmitTrainingPullUpCommand }

    pullup.create_goal.handler:
        class: PullUpService\Handler\CreateGoalHandler
        arguments:
          - '@pullup.goal.repository'
          - '@pullup.exercise.repository'
          - '@pullup.section.repository'
          - '@pullup.current_user'
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\CreateGoalCommand }

    pullup.create_exercise.handler:
        class: PullUpService\Handler\CreateExerciseHandler
        arguments:
          - '@pullup.exercise.repository'
          - '@pullup.current_user'
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\CreateExerciseCommand }

    pullup.update_goal.handler:
        class: PullUpService\Handler\UpdateGoalHandler
        arguments:
          - '@pullup.goal.repository'
          - '@pullup.current_user'
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\UpdateGoalCommand }

    pullup.disable_goal.handler:
        class: PullUpService\Handler\DisableGoalHandler
        arguments:
          - '@pullup.goal.repository'
          - '@pullup.current_user'
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\DisableGoalCommand }

    pullup.create_goal_set.handler:
        class: PullUpService\Handler\CreateGoalSetHandler
        arguments:
          - '@pullup.goal.repository'
          - '@pullup.goal_set.repository'
          - '@pullup.current_user'
          - "@event_bus"
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\CreateGoalSetCommand }

    pullup.update_settings.handler:
        class: PullUpService\Handler\UpdateSettingsHandler
        arguments:
          - '@pullup.user.repository'
          - '@pullup.current_user'
          - "@event_bus"
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\UpdateSettingsCommand }

    pullup.create_section.handler:
        class: PullUpService\Handler\CreateSectionHandler
        arguments:
          - '@pullup.section.repository'
          - '@pullup.current_user'
          - "@event_bus"
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\CreateSectionCommand }

    pullup.move_goal_to_section.handler:
        class: PullUpService\Handler\MoveGoalToSectionHandler
        arguments:
          - '@pullup.section.repository'
          - '@pullup.goal.repository'
          - '@pullup.current_user'
          - "@event_bus"
          - '%kernel.logs_dir%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\MoveGoalToSectionCommand }

    pullup.update_user_device_id.handler:
        class: PullUpService\Handler\UpdateUserDeviceIdHandler
        arguments:
          - '@pullup.user.repository'
          - '@pullup.current_user'
          - '%aws_key%'
          - '%aws_secret%'
        tags:
            - { name: command_handler, handles: PullUpService\Command\UpdateUserDeviceIdCommand }
