PullUpDomain\Entity\User:
    type: entity
    table: user
    repositoryClass: PullUpBundle\Repository\UserRepository
    id:
        id:
            type: uuid
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator

    fields:

        facebookId:
            column: facebook_id
            type: bigint
            nullable: true

        name:
            column: name
            type: string
            length: 24

        deviceId:
            column: device_id
            type: string
            length: 64    

        amazonArn:
            column: amazon_arn
            type: string
            length: 140
            nullable: true
            options:
                default: NULL

        avatar:
            column: avatar
            type: text
            nullable: true

        daysPerCircuit:
            column: days_per_circuit
            type: integer
            length: 3
            options:
                default: 7

        plannerCustomMode:
            column: planner_custom_mode
            type: boolean
            options:
                default: false

        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            column: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update

        expiresAt:
            type: datetime
            options:
                default: "2020-12-31 23:59:59"

    oneToOne:
        trainingPullUpFirstForm:
            targetEntity: PullUpDomain\Entity\TrainingPullUpFirstForm
            inversedBy: user
            cascade: [persist]
            joinColumn:
                name: training_pull_up_first_form_id
                referencedColumnName: id

    oneToMany:
        trainingPullUps:
            targetEntity: PullUpDomain\Entity\TrainingPullUp
            mappedBy: user
            cascade: [persist]

        circuits:
            targetEntity: PullUpDomain\Entity\Circuit
            mappedBy: user
            cascade: [persist]